<?php
/**
 * Created by PhpStorm.
 * User: marcus.vinicius
 * Date: 27/08/2018
 * Time: 09:31
 */

namespace Paggcerto\Service;


use stdClass;

class BusinessActivityService extends PaggcertoService
{
    const SEARCH_BUSINESS_ACTIVITIES = "v2/business-activities";

    /**
     * @param array $routeParams
     * @param array $queryString
     * @param string $path
     * @return mixed
     */
    public function getRequest($routeParams = [], $queryString = [], $path = BusinessActivityService::SEARCH_BUSINESS_ACTIVITIES)
    {
        return parent::getRequest($routeParams, $queryString, $path); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed|void
     */
    protected function init()
    {
        $this->data = new stdClass();
        $this->data->businessActivities = [];
    }

    /**
     * @param stdClass $response
     * @return mixed
     */
    protected function fillEntity(stdClass $response)
    {
        $this->data->businessActivities = [];
        foreach ($response->businessActivities as $businessActivity) {
            $temp = new stdClass();
            $temp->id = $this->getIfSet("id", $businessActivity);
            $temp->name = $this->getIfSet("name", $businessActivity);
            array_push($this->data->businessActivities, $temp);
        }

        return $this->data->businessActivities;
    }
}