<?php
/**
 * Created by PhpStorm.
 * User: marcus.vinicius
 * Date: 24/08/2018
 * Time: 17:48
 */

namespace Paggcerto\Service;

use stdClass;

class BusinessTypeService extends PaggcertoService
{
    const SEARCH_BUSINESS_TYPES = "v2/business-types";

    /**
     * @param array $routeParams
     * @param array $queryString
     * @param string $path
     * @return mixed
     */
    public function getRequest($routeParams = [], $queryString = [], $path = BusinessTypeService::SEARCH_BUSINESS_TYPES)
    {
        return parent::getRequest($routeParams, $queryString, $path); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed|void
     */
    protected function init()
    {
        $this->data = new stdClass();
        $this->data->businessTypes = [];
    }

    /**
     * @param stdClass $response
     * @return mixed
     */
    protected function fillEntity(stdClass $response)
    {
        $this->data->businessTypes = [];
        foreach ($response->businessTypes as $bussinesType) {
            $temp = new stdClass();
            $temp->id = $this->getIfSet("id", $bussinesType);
            $temp->name = $this->getIfSet("name", $bussinesType);
            $temp->acronym = $this->getIfSet("acronym", $bussinesType);
            array_push($this->data->businessTypes, $temp);
        }

        return $this->data->businessTypes;
    }
}